// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk5bKF9nrgDGawDpa4nobm8mWwKj7k_pc',
    appId: '1:768687018055:web:d68bbafd39c540f5526162',
    messagingSenderId: '768687018055',
    projectId: 'nitmhub',
    authDomain: 'nitmhub.firebaseapp.com',
    storageBucket: 'nitmhub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpcr64ouab8dbuRJLC217CrUeBsEqZigQ',
    appId: '1:768687018055:android:a682540633fec0bd526162',
    messagingSenderId: '768687018055',
    projectId: 'nitmhub',
    storageBucket: 'nitmhub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBlvOyzuEq2SOT1Sh4yht447mBfxLyy18',
    appId: '1:768687018055:ios:b8ebe3cb85fd58ac526162',
    messagingSenderId: '768687018055',
    projectId: 'nitmhub',
    storageBucket: 'nitmhub.appspot.com',
    iosBundleId: 'com.example.nitmHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBlvOyzuEq2SOT1Sh4yht447mBfxLyy18',
    appId: '1:768687018055:ios:e5385650ae326f87526162',
    messagingSenderId: '768687018055',
    projectId: 'nitmhub',
    storageBucket: 'nitmhub.appspot.com',
    iosBundleId: 'com.example.nitmHub.RunnerTests',
  );
}
